### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by enescaglayan** [HypheX/trello-v1#4]
the api isn't working.
i use latest release

Script i use:
```
local Trello = require(script.Trello.Main)
local MainBoard = Trello:GetBoardByName("MyGameBanList")
local Banned = MainBoard:GetListByName('Banned')

game:GetService('Players').PlayerAdded:Connect(function(Player)
	local isBanned = Banned:GetCardByName(tostring(Player.Name))
	if isBanned then
		Player:Kick("You have been banned from this game.")
	end
end)
```

auth script in the Trello folder

`return "?key=3742125b5825461b287d56fad5b34b67&token=9b75d7eb6f6138e77f440ec54959d3b3232ba14a8d2fc7ff223c236d83793510"`

i also use the token given by nstrike15's TrelloAPI that gave me a auth link named "Roblox Api" app thingy
i use key from https://trello.com/app-key

my board is https://trello.com/b/rEThsC9O/mygamebanlist and its public

**Comment by ddavness** [comment]
In an attempt to try a reproduction, it seems to work.

Your issue is that you need to Enable HTTP Requests for the module to work:
![image](https://user-images.githubusercontent.com/45321798/61547860-2a8ea400-aa44-11e9-94d4-7f0b6009c85d.png)

Maybe it's worth it to have some extra checks in place. Might write a PR in the future.

**Comment by ddavness** [comment]
Other quirks you might want to know about:

```lua
local Trello = require(script.Trello.Main)
local MainBoard = Trello:GetBoardByName("MyGameBanList")
local Banned = MainBoard:GetListByName('Banned')
```

In an ideal world, this would load instantly. But since that this requires external data (from Trello), it will yield. So when you finally get to set up the `PlayerAdded` event, it's likely that someone had joined already and didn't get checked.

**Solution:**

```lua
local Trello = require(script.Trello.Main)
local MainBoard = Trello:GetBoardByName("MyGameBanList")
local Banned = MainBoard:GetListByName('Banned')

function checkBanned(Player)
	local isBanned = Banned:GetCardByName(tostring(Player.Name))
	print(isBanned)
	if isBanned then
		Player:Kick("You have been banned from this game.")
	end
end

-- Check for players yet to come
game:GetService('Players').PlayerAdded:Connect(checkBanned)

-- Check for players that already arrived
for _,p in pairs(game:GetService('Players'):GetPlayers()) do
	checkBanned(p)
end

print("All set!")
```

**Comment by HypheX** [comment]
Indeed, many people have had problems before, as they put their PlayerAdded event after a fetch from trello, meaning it never fired.
